import type { Content } from "./types";

export const content: Content = {
  nav_about: "About",
  nav_services: "Expertise",
  nav_geo: "Geography",
  nav_contact: "Contact",
  hero_label: "Lighting trading & engineering",
  hero_line1: "Global sourcing of",
  hero_line2: "professional",
  hero_sub:
    "We connect large-scale projects with the best factories in Asia and Europe. Full cycle: from lighting audit and factory selection to quality control in China and final delivery to site.",
  hero_cta: "Discuss your project",
  video_label: "Watch company video",
  about_label: "About",
  about_quote:
    "We are a reliable bridge between production lines and your construction site",
  about_text:
    "RayStream International Limited was created as a modern hub for international trade. Our foundation is a synergy of professionals: IT project managers, experienced logistics specialists, lighting engineers and designers.",
  about_text2:
    "Our team's practical experience in infrastructure and hotel projects across CIS and the Middle East dates back to 2005. We've combined established supply chains, systematic management and deep technical expertise to make equipment exports transparent, precise and predictable.",
  m_years: "Years of team experience",
  m_projects: "Audits and projects delivered",
  m_factories: "Verified factory partners",
  m_regions: "Key supply regions",
  serv_label: "Expertise",
  serv_h2: "Areas of activity",
  s1_h: "Industrial & infrastructure lighting",
  s1_p: "Reliable equipment for warehouses, production facilities and sports arenas. High resistance to aggressive environments (IP66+, IK08+, vibration resistant).",
  s2_h: "Architectural & landscape lighting",
  s2_p: "Specialized optics for facade lighting, media facades and area illumination. Solutions for landmark urban projects and hospitality complexes.",
  s3_h: "Commercial & interior lighting",
  s3_p: "Professional solutions for hotels, business centers, retail and restaurants. Strict visual comfort compliance (CRI >90, low UGR).",
  s4_h: "LED technology & intelligent control",
  s4_p: "Energy-efficient systems with full integration of control protocols (DALI, DMX, KNX). Automation for dynamic scenarios and cost reduction.",
  adv_label: "Advantages",
  adv_h2: "Why choose us",
  a1_h: "Engineering approach",
  a1_p: "Certified lighting engineers work on specifications. We evaluate photometry, thermal management and component quality.",
  a2_h: "Lighting audit",
  a2_p: "We perform DIALux calculations and select precise alternatives for budget optimization (Value Engineering).",
  a3_h: "Direct quality control",
  a3_p: "Our local team in China physically inspects equipment and verifies assembly at factories before shipment.",
  a4_h: "Transparent logistics",
  a4_p: "We consolidate cargo from different factories, deliver to site and fully transfer manufacturer warranties.",
  geo_label: "Geography",
  geo_h2: "Global supply network",
  geo_desc:
    "Our Hong Kong headquarters ensures direct financial and trade operations with factories. The engineering hub in Tashkent guarantees responsive technical support and project management. Leveraging a network of local partners, we've built seamless logistics across China, UAE, Turkey and CIS countries.",
  gs_years: "years of experience",
  gs_factories: "factory partners",
  gs_regions: "supply regions",
  part_label: "Partners",
  ct_label: "Contact",
  ct_h2: "Ready to optimize your project?",
  ct_sub:
    "Request a cargo consolidation estimate or a professional lighting audit of your specification.",
  f_name: "Name",
  f_name_ph: "Your name",
  f_email: "Email",
  f_msg: "Message",
  f_msg_ph: "Tell us about your project...",
  f_submit: "Send request",
  f_sending: "Sending...",
  f_success: "Request sent!",
  f_error: "Failed to send. Please try again.",
};
